
name: Release Rust Binary with Cross

on:
  push:
    tags:
      - 'v*'  # Trigger on tags like 'v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-musl, x86_64-pc-windows-gnu, aarch64-unknown-linux-gnu]

    env:
      BINARY_NAME: commr

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Cross
        run: cargo install cross

      - name: Build with Cross
        run: cross build --target ${{ matrix.target }} --release

      - name: Create Release Archive
        run: |
          mkdir -p release

          if [[ "${{ matrix.target }}" == *"windows"* ]]; then
            cp target/${{ matrix.target }}/release/${{ env.BINARY_NAME }}.exe release/
            zip -r ${{ matrix.target }}.zip release
          else
            cp target/${{ matrix.target }}/release/${{ env.BINARY_NAME }} release/
            tar -czvf ${{ matrix.target }}.tar.gz -C release ${{ env.BINARY_NAME }}
          fi

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.tar.gz
            *.zip
        env:
          GITHUB_TOKEN: ${{ secrets.COMMR }}

